### ISSUE TITLE
python 3 and block=false

### ISSUE THREAD

**Issue by AchimP61** [akkana/scripts#8]
Hey, I'd like to use your class for python 3 and with block=false. However, if I change the shebang to
#!/usr/bin/env python3
and the main initializer to
    keyreader = KeyReader(echo=False, block=False)
upon calling the Keyreader.py from command prompt I receive an error

johndoe@raspberrypi:~/git/raspberry/rolladen$ KeyReader.py
Traceback (most recent call last):
  File "./KeyReader.py", line 104, in <module>
    main()
  File "./KeyReader.py", line 93, in main
    key = keyreader.getch()
  File "./KeyReader.py", line 84, in getch
    return sys.stdin.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by akkana** [comment]
Thanks for the report. It turns out that in Python 3, a non-blocking read when there's nothing to read now raises TypeError instead of the more sensible IOError. This fix should make it work in either Python version. I also added a short sleep in the non-blocking testing code in __main__ to make it easier to see if it's working.
